name: versionpulse-run

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs at midnight UTC every 2 days
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Set your Go version here

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run the main.go file
      - name: Run main.go
        env:
          VP_API_KEY: ${{ secrets.VP_API_KEY }}
        run: | 
           go run main.go
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add feed.json
           git commit -m "Update feed.json [skip ci]" || echo "No changes to commit"
           git push